#! /bin/bash

fail=0
if [ ! -x `which aclocal` ]; then
    echo "aclocal is missing, please install automake (e.g., sudo apt-get install automake)"
    fail=1
fi

if [ ! -x `which libtoolize` ]; then
    echo "libtoolize is missing, please install libtool (e.g., sudo apt-get install libtool)"
    fail=1
fi

if [ $fail -eq 1 ]; then
    echo "Stopped."
    exit 1;
fi

echo "Running autotools..."

aclocal \
&& libtoolize --force \
&& autoheader \
&& automake -a --foreign --add-missing \
&& autoreconf

echo "Done."
echo "Now type:"
echo "> ./configure"
echo "> make"
echo "> make install"

